### ISSUE TITLE
Axiomatic behaviour 

### ISSUE THREAD

**Issue by jacobfriedman** [thetrime/proactive#8]
I understand it's ideal to code in react-like syntax...

Why have you not opted to declare your structures in the `element(Element,[][])` -like syntax, and create new clauses or predicates for the appropriate structures (letting axioms do their work)? Is it because you wanted to get the browser-events (e.g. componentLoaded/Mount)

**Comment by thetrime** [comment]
If you're asking why I opted for <div> instead of element(div, [], []), then it's the same reason people usually code in JSX when using React - it's a lot more compact and readable. 

I should mention that I haven't done any work on this for a really long time now. There's a newer project proactive2 which has a React-first approach that might be a bit more useful if you're interested... though I haven't worked on that for about a year now either :(

**Comment by jacobfriedman** [comment]
I see- thanks for the heads up. I went to vanilla & am working on a mutationObserver method to a prolog engine at any rate, but I was curious to see who you wanted to integrate with / why. For example, the SWI method is the element(..., and Raivo Laanemets uses another as well.  Good to know. Hope our paths cross in the future - there's a lot of promise with prolog in the browser.
